### PR TITLE
Add's a guide page on clustering Disnake bots

### PR DESCRIPTION
**Pull request by Skelmis**
## Description

This PR adds a new page to the guide which discusses a simplistic way to cluster any Disnake bot with guided examples for the every day user.

## Relevant Issues

1. Arl said "probably" to the content.
2. There doesn't exist enough resources on clustering in the Disnake, and by extension the Python discord bot community

This is blocked by a couple third party items I wish to clear before any merges. Expect this to be ready for review by the end of the weekend.

### CODE REVIEW

**Comment by onerandomusername** [comment]
Hi, would you please rebase onto master to fix merge conflicts?

**Comment by onerandomusername** [comment]
@Skelmis what happened to package-lock.json?

**Comment by Skelmis** [comment]
Remarking as draft pending a move to ghcr for all examples in the guide. 

This may take awhile as I want to test it all etc as I'm only familiar with the methods already described here

**Comment by Skelmis** [comment]
As much as I would love for this to be in the guide, I do not currently have the time required to resolve the reviews on this pull request to a standard both I and the maintainers would be happy with. 

This may be reopened if I get to a stage where I have found time to make the required changes / test and streamline them.

**Pull request closed without merging**
